# Site settings
title: GMM
description: Give Me Money
keywords: GMM
baseurl: "/GMM"
url: https://copoDOG.github.io/
remote_theme: Jekyll_modern-blog-gh-pages
repository: copoDOG/copoDOG.github.io
repository_tree: master
paths:
  root    : /index.html
  home    : /index.html
  archive :
  rss     :
